[package]
name = "iban_validate_afl_fuzz"
version = "0.1.0"
authors = ["thomasdh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iban_validate = { path = "../iban_validate" }
afl = "0.10"
